### ISSUE TITLE
Feature Request: Choose which file to download

### ISSUE THREAD

**Issue by Ramzh** [thophys/yiff_scraper#2]
Would be great if the program allowed to decided which file in post-attachment to download, e.g. download only jpeg, jpg, etc.

Currently using the following:
```
{
    "patreonCreatorsToDownload": [
      2648863
    ],
    "downlaodsOutputFolder": "C:/Users/Norman/Desktop/yiff/exe/img",
    "enableCategories": true,
    "downloadCaterories": [
      {
        "name": "images",
        "fileTypes": [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tif", ".tiff"]
      }
    ],
    "replaceExistingFiles": false,
    "checkForCorruptedFiles": false,
    "saveExternalLinksToTxt": true,
    "withVerbose": false,
    "saveLog": false
  }
```

But it still gets the .psd and others in the misc folder

**Comment by thophys** [comment]
Would it help if I add a flag to ignore uncategorized files?
But that wouldn't work without "enableCategories"

**Comment by thophys** [comment]
I added a new flag: "ignoreUncategorizedFileTypes" that you can set to true, and it will only dowlnoad the files whose extensions correspont to a category you setup, if no category is found for that fileType, it won't be downloaded.

https://github.com/thophys/yiff_scraper/releases/tag/0.7.0
