### ISSUE TITLE
Error 503?

### ISSUE THREAD

**Issue by Ramzh** [thophys/yiff_scraper#3]
`{"message":"Request failed with status code 503","name":"Error","stack":"Error: Request failed with status code 503\n    at createError (C:\\snapshot\\yiff_scraper\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\snapshot\\yiff_scraper\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\snapshot\\yiff_scraper\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1218:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"https://yiff.party/render_posts?s=patreon&c=2648863&p=5","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"document","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`

Got the above, looks like an HTTP error but yiff.party page works fine

Any clue?

**Comment by thophys** [comment]
Is it constant? I mean, it happens every time you run?
503 usually means that the server might be overloaded

**Comment by Ramzh** [comment]
> Is it constant? I mean, it happens every time you run?
> 503 usually means that the server might be overloaded

Yes unfortunately. That's what I thought but yiff working fine so thought this could have been a node module giving issue

**Comment by Ramzh** [comment]
So did some tests and seems like the issue only appears in 0.7.0 while 0.6.3 works fine. Hope this helps to tackle the bug

**Comment by thophys** [comment]
i found the problem, sorry for the delay, i had changed it to parallel requests, but apparently something changed in their server that doesn't allow it as anymore, so i reverted it.
here's the new version with that bug fixed: https://github.com/thophys/yiff_scraper/releases/tag/0.7.1

**Comment by Ramzh** [comment]
Awesome! Thank you very much!
