### ISSUE TITLE
Loading creator error

### ISSUE THREAD

**Issue by Ramzh** [thophys/yiff_scraper#5]
Just downloaded the new version but seems like it gets stuck after loading the creator without iterating through the pages:

```
Loading config...
Loading config done!
Validating configuration...
Validating configuration done!
[21/07/2020, 16:33:28]  Initializing patreon downloader
[21/07/2020, 16:33:28]  Loading basic creators info...
[21/07/2020, 16:33:28]  Loading basic creators info done!
[21/07/2020, 16:33:28]  Loading detailed creators info...
[21/07/2020, 16:33:29]  Loading creator nanoless posts...
[21/07/2020, 16:33:29]  Loading creator https://yiff.party/patreon/990234
Nanoless (nanoless)|0-17 pages => [----------------------------------------] 0%[21/07/2020, 16:33:33]  {}
```

Current JSON:
```
  {
    "patreonCreatorsToDownload": [
      990234
    ],
    "fantiaCreatorsToDownload": [  ],
    "downlaodsOutputFolder": "C:/Users/TAICHI/Desktop/yiff/exe/img",
    "enableCategories": true,
    "ignoreUncategorizedFileTypes": true,
    "downloadCategories": [
      {
        "name": "images",
        "fileTypes": [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tif", ".tiff"]
      }
    ],
    "replaceExistingFiles": false,
    "checkForCorruptedFiles": false,
    "saveExternalLinksToTxt": true,
    "withVerbose": false,
    "saveLog": false
  }
```

**Comment by thophys** [comment]
For what i tested it is indeed stuck, but it also didn't load on my browser, does it load on yours?

**Comment by thophys** [comment]
the yiff website is back online to me, i was able to download with no problems, tell me if you're still having any issue

**Comment by Ramzh** [comment]
Apologies for the delay. I still have issue. Basically as soon as I run the exe it says the above output but then the cmd closes itself. 

yiff was working for me earlier and now as well. Not sure what's going on, I tried to redownload and create the JSON from scratch but can't make it work. It just loads up and closes itself

**Comment by thophys** [comment]
Try this: https://github.com/thophys/yiff_scraper/releases/tag/0.7.2
tell me if it works

**Comment by Ramzh** [comment]
Yep working fine!
